import { api } from './client'
import type { AuditLog, CertificateItem, Inquiry, Product, ProductCategory, SessionItem, SiteModel, UploadItem, UserItem } from '../types'

export const getSiteModel = () => api<SiteModel>('/api/admin/site-model')
export const updateSiteSection = (section: string, payload: unknown) => api(`/api/admin/site-model/${section}`, { method: 'PUT', body: JSON.stringify(payload) })
export const getInquiries = () => api<Inquiry[]>('/api/inquiries')
export const updateInquiry = (id: string, payload: Partial<Inquiry>) => api(`/api/inquiries/${id}`, { method: 'PUT', body: JSON.stringify(payload) })
export const getCategories = () => api<ProductCategory[]>('/api/product-categories')
export const createCategory = (payload: Partial<ProductCategory>) => api('/api/product-categories', { method: 'POST', body: JSON.stringify(payload) })
export const updateCategory = (id: string, payload: Partial<ProductCategory>) => api(`/api/product-categories/${id}`, { method: 'PUT', body: JSON.stringify(payload) })
export const deleteCategory = (id: string) => api(`/api/product-categories/${id}`, { method: 'DELETE' })
export const getProducts = () => api<Product[]>('/api/products')
export const createProduct = (payload: Partial<Product>) => api('/api/products', { method: 'POST', body: JSON.stringify(payload) })
export const updateProduct = (id: string, payload: Partial<Product>) => api(`/api/products/${id}`, { method: 'PUT', body: JSON.stringify(payload) })
export const deleteProduct = (id: string) => api(`/api/products/${id}`, { method: 'DELETE' })
export const getCertificates = () => api<CertificateItem[]>('/api/certificates')
export const createCertificate = (payload: Partial<CertificateItem>) => api('/api/certificates', { method: 'POST', body: JSON.stringify(payload) })
export const updateCertificate = (id: string, payload: Partial<CertificateItem>) => api(`/api/certificates/${id}`, { method: 'PUT', body: JSON.stringify(payload) })
export const deleteCertificate = (id: string) => api(`/api/certificates/${id}`, { method: 'DELETE' })
export const getUploads = () => api<UploadItem[]>('/api/uploads')
export const uploadAsset = (payload: { name: string; base64: string }) => api<{ url: string }>('/api/uploads', { method: 'POST', body: JSON.stringify(payload) })
export const getUsers = () => api<UserItem[]>('/api/users')
export const createUser = (payload: { username: string; password: string; role: string }) => api('/api/users', { method: 'POST', body: JSON.stringify(payload) })
export const deleteUser = (username: string) => api(`/api/users/${username}`, { method: 'DELETE' })
export const changePassword = (payload: { password: string }) => api('/api/users/password', { method: 'PUT', body: JSON.stringify(payload) })
export const getAuditLogs = () => api<AuditLog[]>('/api/audit-logs')
export const getSessions = () => api<SessionItem[]>('/api/session-store')
export const deleteSession = (token: string) => api(`/api/session-store/${token}`, { method: 'DELETE' })
